import "./globals.css";
import ClientProviders from "@/components/ClientProviders";

export const metadata = {
  title: "FreshMart",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ClientProviders>
          {children}
        </ClientProviders>
      </body>
    </html>
  );
}
