const products = [
  {
    title: "Iso Whey Protein Isolate",
    slug: "iso-whey-protein-isolate",
    units: [{ unit: "2 Kg", price: 4200, discount: 18, finalPrice: 3444 }],
    views: 520,
    shelfLife: "18 months",
    stock: 55,
    isBestSeller: true,
    isNewLaunch: false,
    isSuperSaver: false,
    totalSold: 680,
    status: "active",
    returnPolicy: { returnable: false },
    countryOfOrigin: "USA",
    description: "Ultra-pure whey protein isolate for lean muscle.",
    features: "30g Protein, Low carb, Fast absorption",
    category: "men",
    subcategory:"multivitamins",
  
    brand: "muscle-gear",
    tag: ["premium"],
    images: ["/images/img1.jpg"],
  },
  {
    title: "Body Health Multivitamins",
    slug: "body-health-multivitamins",
    units: [{ unit: "60 Caps", price: 850, discount: 15, finalPrice: 722 }],
    views: 340,
    shelfLife: "24 months",
    stock: 100,
    isBestSeller: true,
    isNewLaunch: true,
    isSuperSaver: false,
    totalSold: 210,
    status: "active",
    returnPolicy: { returnable: true },
    countryOfOrigin: "India",
    description: "Daily essential nutrients for body health.",
    features: "Immune support, Energy boost",
    category: "child",
    subcategory:"multivitamins",
    brand: "vital-health",
    tag: ["fitness"],
    images: ["/images/img2.jpg"],
  },
  {
    title: "Whey Protein Powder",
    slug: "whey-protein-powder",
    units: [{ unit: "1 Kg", price: 2800, discount: 20, finalPrice: 2240 }],
    views: 500,
    shelfLife: "18 months",
    stock: 60,
    isBestSeller: true,
    isNewLaunch: false,
    isSuperSaver: false,
    totalSold: 890,
    status: "active",
    returnPolicy: { returnable: false },
    countryOfOrigin: "USA",
    description: "Muscle recovery and muscle building formula.",
    features: "25g Protein, Zero Sugar",
   category: "men",
    subcategory:"gummies",
    brand: "muscle-gear",
    tag: ["gym-essential"],
    images: ["/images/img3.jpg"],
  },
  {
    title: "Omega-3 Fish Oil Softgels",
    slug: "omega-3-fish-oil",
    units: [{ unit: "30 Softgels", price: 600, discount: 10, finalPrice: 540 }],
    views: 210,
    shelfLife: "18 months",
    stock: 150,
    isBestSeller: false,
    isNewLaunch: false,
    isSuperSaver: true,
    totalSold: 320,
    status: "active",
    returnPolicy: { returnable: true },
    countryOfOrigin: "Norway",
    description: "Heart health and brain function support.",
    features: "Pure EPA/DHA",
   category: "men",
    subcategory:"multivitamins",
    brand: "pure-nature",
    tag: ["heart-health"],
    images: ["/images/img4.jpg"],
  },
  {
    title: "Vitamin C Immunity Booster",
    slug: "vitamin-c-booster",
    units: [{ unit: "60 Tabs", price: 400, discount: 10, finalPrice: 360 }],
    views: 180,
    shelfLife: "24 months",
    stock: 250,
    isBestSeller: true,
    isNewLaunch: false,
    isSuperSaver: false,
    totalSold: 560,
    status: "active",
    returnPolicy: { returnable: true },
    countryOfOrigin: "India",
    description: "Antioxidant support for strong immunity.",
    features: "Natural extracts",
  category: "men",
    subcategory:"gummies",
    brand: "vital-health",
    tag: ["immunity"],
    images: ["/images/img5.jpg"],
  },
  {
    title: "Casein Protein Night Formula",
    slug: "casein-protein-night",
    units: [{ unit: "1 Kg", price: 3200, discount: 15, finalPrice: 2720 }],
    views: 285,
    shelfLife: "18 months",
    stock: 70,
    isBestSeller: false,
    isNewLaunch: true,
    isSuperSaver: false,
    totalSold: 195,
    status: "active",
    returnPolicy: { returnable: false },
    countryOfOrigin: "USA",
    description: "Slow-release protein for overnight recovery.",
    features: "Micellar Casein, 24g Protein",
   category: "men",
    subcategory:"multivitamins",
    brand: "muscle-gear",
    tag: ["recovery"],
    images: ["/images/img6.jpg"],
  },
  {
    title: "Calcium & Vitamin D3 Tablets",
    slug: "calcium-d3-tablets",
    units: [{ unit: "100 Tabs", price: 550, discount: 5, finalPrice: 522 }],
    views: 155,
    shelfLife: "24 months",
    stock: 300,
    isBestSeller: false,
    isNewLaunch: false,
    isSuperSaver: false,
    totalSold: 130,
    status: "active",
    returnPolicy: { returnable: true },
    countryOfOrigin: "India",
    description: "For bone strength and joint health.",
    features: "Maximum absorption",
  category: "men",
    subcategory:"gummies",
    brand: "pure-nature",
    tag: [],
    images: ["/images/img7.jpg"],
  },
  {
    title: "Vegan Plant Protein Blend",
    slug: "vegan-plant-protein",
    units: [{ unit: "1 Kg", price: 2400, discount: 20, finalPrice: 1920 }],
    views: 365,
    shelfLife: "18 months",
    stock: 90,
    isBestSeller: true,
    isNewLaunch: false,
    isSuperSaver: false,
    totalSold: 450,
    status: "active",
    returnPolicy: { returnable: false },
    countryOfOrigin: "India",
    description: "Complete plant-based protein from pea & rice.",
    features: "22g Protein, Dairy-free, Vegan",
   category: "men",
    subcategory:"powder",
    brand: "nature-picks",
    tag: ["vegan"],
    images: ["/images/img8.jpg"],
  },
  {
    title: "Organic Ashwagandha Extract",
    slug: "ashwagandha-extract",
    units: [{ unit: "60 Caps", price: 650, discount: 20, finalPrice: 520 }],
    views: 290,
    shelfLife: "36 months",
    stock: 120,
    isBestSeller: true,
    isNewLaunch: false,
    isSuperSaver: false,
    totalSold: 440,
    status: "active",
    returnPolicy: { returnable: true },
    countryOfOrigin: "India",
    description: "Ayurvedic stress relief and wellness.",
    features: "KSM-66 certified",
  category: "men",
    subcategory:"multivitamins",
    brand: "nature-picks",
    tag: ["ayurvedic"],
    images: ["/images/img9.jpg"],
  },
  {
    title: "BCAA Energy Drink Mix",
    slug: "bcaa-energy-drink",
    units: [{ unit: "500g", price: 1200, discount: 25, finalPrice: 900 }],
    views: 380,
    shelfLife: "18 months",
    stock: 75,
    isBestSeller: true,
    isNewLaunch: false,
    isSuperSaver: false,
    totalSold: 670,
    status: "active",
    returnPolicy: { returnable: false },
    countryOfOrigin: "USA",
    description: "Pre-workout energy and muscle recovery.",
    features: "2:1:1 ratio, Electrolytes",
    category: "men",
    subcategory:"multivitamins",
    brand: "muscle-gear",
    tag: ["gym-essential"],
    images: ["/images/img10.jpg"],
  },


  {
    title: "Zinc & Magnesium Capsules",
    slug: "zinc-magnesium-caps",
    units: [{ unit: "90 Caps", price: 480, discount: 12, finalPrice: 422 }],
    views: 195,
    shelfLife: "24 months",
    stock: 180,
    isBestSeller: false,
    isNewLaunch: false,
    isSuperSaver: true,
    totalSold: 285,
    status: "active",
    returnPolicy: { returnable: true },
    countryOfOrigin: "India",
    description: "Essential minerals for recovery and sleep.",
    features: "Enhanced absorption formula",
   category: "men",
    subcategory:"powder",
    brand: "vital-health",
    tag: ["recovery"],
    images:["/images/img11.jpg"],
  },

  {
    title: "Creatine Monohydrate Powder",
    slug: "creatine-monohydrate",
    units: [{ unit: "300g", price: 950, discount: 18, finalPrice: 779 }],
    views: 445,
    shelfLife: "24 months",
    stock: 95,
    isBestSeller: true,
    isNewLaunch: false,
    isSuperSaver: false,
    totalSold: 780,
    status: "active",
    returnPolicy: { returnable: false },
    countryOfOrigin: "Germany",
    description: "Muscle strength and performance enhancer.",
    features: "Micronized, Unflavored",
    category: "women",
    subcategory:"gummies",
    brand: "muscle-gear",
    tag: ["strength"],
    images:["/images/img12.jpg"],
  },

  {
    title: "Apple Cider Vinegar with Mother",
    slug: "apple-cider-vinegar",
    units: [{ unit: "500ml", price: 320, discount: 15, finalPrice: 272 }],
    views: 265,
    shelfLife: "24 months",
    stock: 140,
    isBestSeller: false,
    isNewLaunch: true,
    isSuperSaver: false,
    totalSold: 195,
    status: "active",
    returnPolicy: { returnable: true },
    countryOfOrigin: "India",
    description: "Natural detox and weight management support.",
    features: "Organic, Unfiltered",
    category: "child",
    subcategory:"multivitamins",
    brand: "nature-picks",
    tag: ["detox"],
    images: ["/images/img13.jpg"],
  },

  {
    title: "Mass Gainer Protein Blend",
    slug: "mass-gainer-protein",
    units: [{ unit: "3 Kg", price: 3500, discount: 22, finalPrice: 2730 }],
    views: 410,
    shelfLife: "18 months",
    stock: 45,
    isBestSeller: true,
    isNewLaunch: false,
    isSuperSaver: false,
    totalSold: 520,
    status: "active",
    returnPolicy: { returnable: false },
    countryOfOrigin: "USA",
    description: "High-calorie formula for muscle mass gain.",
    features: "50g Protein, Complex carbs",
   category: "women",
    subcategory:"gummies",
    brand: "muscle-gear",
    tag: ["bulking"],
    images: ["/images/img14.jpg"],
  },

  {
    title: "Turmeric Curcumin Capsules",
    slug: "turmeric-curcumin",
    units: [{ unit: "60 Caps", price: 580, discount: 10, finalPrice: 522 }],
    views: 225,
    shelfLife: "36 months",
    stock: 160,
    isBestSeller: false,
    isNewLaunch: false,
    isSuperSaver: true,
    totalSold: 340,
    status: "active",
    returnPolicy: { returnable: true },
    countryOfOrigin: "India",
    description: "Natural anti-inflammatory and joint support.",
    features: "95% Curcuminoids, BioPerine",
    category: "child",
    subcategory:"multivitamins",
    brand: "pure-nature",
    tag: ["anti-inflammatory"],
    images: ["/images/img15.jpg"],
  },

  {
    title: "Probiotic Digestive Support",
    slug: "probiotic-digestive",
    units: [{ unit: "30 Caps", price: 720, discount: 15, finalPrice: 612 }],
    views: 188,
    shelfLife: "18 months",
    stock: 110,
    isBestSeller: false,
    isNewLaunch: true,
    isSuperSaver: false,
    totalSold: 165,
    status: "active",
    returnPolicy: { returnable: true },
    countryOfOrigin: "USA",
    description: "Gut health and digestive wellness formula.",
    features: "10 Billion CFU, 10 strains",
    category: "women",
    subcategory:"powder",
    brand: "vital-health",
    tag: ["digestive"],
    images: ["/images/img16.jpg"],
  },

  {
    title: "L-Carnitine Fat Burner",
    slug: "l-carnitine-burner",
    units: [{ unit: "60 Caps", price: 990, discount: 20, finalPrice: 792 }],
    views: 355,
    shelfLife: "24 months",
    stock: 85,
    isBestSeller: true,
    isNewLaunch: false,
    isSuperSaver: false,
    totalSold: 465,
    status: "active",
    returnPolicy: { returnable: false },
    countryOfOrigin: "USA",
    description: "Supports metabolism and fat loss.",
    features: "500mg per serving, Vegan",
    category: "women",
    subcategory:"multivitamins",
    brand: "muscle-gear",
    tag: ["weight-loss"],
    images: ["/images/img17.jpg"],
  },

  {
    title: "Collagen Peptides Powder",
    slug: "collagen-peptides",
    units: [{ unit: "300g", price: 1400, discount: 18, finalPrice: 1148 }],
    views: 310,
    shelfLife: "24 months",
    stock: 70,
    isBestSeller: true,
    isNewLaunch: false,
    isSuperSaver: false,
    totalSold: 390,
    status: "active",
    returnPolicy: { returnable: true },
    countryOfOrigin: "Brazil",
    description: "Skin, hair, and joint health support.",
    features: "Type I & III, Unflavored",
    category: "women",
    subcategory:"powder",
    brand: "pure-nature",
    tag: ["beauty"],
    images: ["/images/img18.jpg"],
  },

  {
    title: "Glutamine Muscle Recovery",
    slug: "glutamine-recovery",
    units: [{ unit: "250g", price: 850, discount: 15, finalPrice: 722 }],
    views: 275,
    shelfLife: "24 months",
    stock: 105,
    isBestSeller: false,
    isNewLaunch: false,
    isSuperSaver: true,
    totalSold: 310,
    status: "active",
    returnPolicy: { returnable: false },
    countryOfOrigin: "USA",
    description: "Post-workout recovery and immune support.",
    features: "5g per serving, Pharmaceutical grade",
    category: "women",
    subcategory:"multivitamins",
    brand: "muscle-gear",
    tag: ["recovery"],
    images: ["/images/img19.jpg"],
  },

  {
    title: "Biotin Hair Growth Tablets",
    slug: "biotin-hair-growth",
    units: [{ unit: "60 Tabs", price: 450, discount: 10, finalPrice: 405 }],
    views: 240,
    shelfLife: "24 months",
    stock: 190,
    isBestSeller: false,
    isNewLaunch: false,
    isSuperSaver: false,
    totalSold: 280,
    status: "active",
    returnPolicy: { returnable: true },
    countryOfOrigin: "India",
    description: "Supports healthy hair, skin, and nails.",
    features: "10,000mcg per tablet",
    category: "women",
    subcategory:"multivitamins",
    brand: "vital-health",
    tag: ["hair-care"],
    images: ["/images/img20.jpg"],
  },

  {
    title: "Green Tea Extract Capsules",
    slug: "green-tea-extract",
    units: [{ unit: "90 Caps", price: 520, discount: 12, finalPrice: 458 }],
    views: 205,
    shelfLife: "24 months",
    stock: 145,
    isBestSeller: false,
    isNewLaunch: true,
    isSuperSaver: false,
    totalSold: 235,
    status: "active",
    returnPolicy: { returnable: true },
    countryOfOrigin: "India",
    description: "Antioxidant and metabolism booster.",
    features: "50% EGCG, Natural caffeine",
     category: "adult",
    subcategory:"multivitamins",
    brand: "nature-picks",
    tag: ["antioxidant"],
    images: ["/images/img21.jpg"],
  },

  {
    title: "Iron + Folic Acid Tablets",
    slug: "iron-folic-acid",
    units: [{ unit: "100 Tabs", price: 380, discount: 8, finalPrice: 350 }],
    views: 165,
    shelfLife: "24 months",
    stock: 220,
    isBestSeller: false,
    isNewLaunch: false,
    isSuperSaver: true,
    totalSold: 295,
    status: "active",
    returnPolicy: { returnable: true },
    countryOfOrigin: "India",
    description: "Supports healthy blood and energy levels.",
    features: "Gentle on stomach",
     category: "adult",
    subcategory:"powder",
    brand: "pure-nature",
    tag: ["anemia"],
    images: ["/images/img22.jpg"],
  },

  {
    title: "Pre-Workout Energy Booster",
    slug: "pre-workout-energy",
    units: [{ unit: "300g", price: 1300, discount: 25, finalPrice: 975 }],
    views: 425,
    shelfLife: "18 months",
    stock: 65,
    isBestSeller: true,
    isNewLaunch: false,
    isSuperSaver: false,
    totalSold: 615,
    status: "active",
    returnPolicy: { returnable: false },
    countryOfOrigin: "USA",
    description: "Explosive energy and focus for workouts.",
    features: "200mg Caffeine, Beta-Alanine",
    category: "adult",
    subcategory:"multivitamins",
    brand: "muscle-gear",
    tag: ["energy"],
    images: ["/images/img23.jpg"],
  },

  {
    title: "Melatonin Sleep Support",
    slug: "melatonin-sleep",
    units: [{ unit: "60 Tabs", price: 480, discount: 10, finalPrice: 432 }],
    views: 198,
    shelfLife: "24 months",
    stock: 175,
    isBestSeller: false,
    isNewLaunch: false,
    isSuperSaver: false,
    totalSold: 325,
    status: "active",
    returnPolicy: { returnable: true },
    countryOfOrigin: "USA",
    description: "Natural sleep aid for restful nights.",
    features: "5mg per tablet, Non-habit forming",
     category: "adult",
    subcategory:"gummies",
    brand: "vital-health",
    tag: ["sleep"],
    images: ["/images/img24.jpg"],
  },
];


export default products;